[project]
name = "lerobot_common_ros2"
version = "0.1.0"
description = "LeRobot ROS 2 common utilities"
readme = "../../README.md"  
requires-python = ">=3.10"

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "lerobot_common_ros2"
module-root = ""